---
abstract: 'Object Oriented Authentication-Results Headers'
author:
  - 'Marc Bradshaw <marc@marcbradshaw.net>'
build_requires:
  Test::Exception: '0'
  Test::More: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mail-AuthenticationResults
requires:
  Carp: '0'
  Clone: '0'
  JSON: '0'
  Scalar::Util: '0'
  base: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
version: '2.20210915'
x_contributors:
  - 'Ricardo Signes <rjbs@users.noreply.github.com>'
x_generated_by_perl: v5.34.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
